# Generated by Django 4.2.16 on 2025-04-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('home_runs', models.IntegerField()),
                ('batting_average', models.FloatField()),
                ('rbis', models.IntegerField()),
                ('stolen_bases', models.IntegerField()),
            ],
        ),
    ]
