# Generated by Django 4.2.16 on 2025-04-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='PlayerStats',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='name',
            new_name='player_name',
        ),
    ]
