# Generated by Django 4.2.16 on 2025-04-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_stats', '0002_rename_player_playerstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='on_base_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='slugging_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='batting_average',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='home_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='rbis',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='stolen_bases',
            field=models.IntegerField(default=0),
        ),
    ]
